# Generated by Django 4.2.11 on 2024-03-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FavMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favtitle', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('poster', models.ImageField(blank=True, upload_to='gallery')),
                ('category', models.CharField(max_length=250)),
                ('desc', models.TextField(blank=True)),
                ('release_date', models.DateField(auto_now=True)),
                ('actor', models.CharField(max_length=250)),
                ('director', models.CharField(max_length=250)),
                ('writer', models.CharField(max_length=250)),
                ('movie_link', models.URLField()),
            ],
            options={
                'verbose_name': 'favmovie',
                'verbose_name_plural': 'favmovies',
                'ordering': ('favtitle',),
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('poster', models.ImageField(blank=True, upload_to='gallery')),
                ('category', models.CharField(max_length=250)),
                ('desc', models.TextField(blank=True)),
                ('release_date', models.DateField(auto_now=True)),
                ('actor', models.CharField(max_length=250)),
                ('director', models.CharField(max_length=250)),
                ('writer', models.CharField(max_length=250)),
                ('movie_link', models.URLField()),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('movie', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now=True)),
                ('review', models.CharField(max_length=250)),
            ],
        ),
    ]
